### ISSUE TITLE
Can't run on OSX

### ISSUE THREAD

**Issue by mandarl** [utamaro/neje-ui#7]
Get below error on OSX. 

/src/github.com/utamaro/neje-ui/webserver/browser.go:69: executing /usr/bin/open -a Google\ Chrome --disable-extension  --app=http://127.0.0.1:53482/ex.html
open: unrecognized option `--disable-extension'
Usage: open [-e] [-t] [-f] [-W] [-R] [-n] [-g] [-h] [-b <bundle identifier>] [-a <application>] [filenames] [--args arguments]
Help: Open opens files from a shell.
      By default, opens each file using the default application for that file.  
      If the file is in the form of a URL, the file will be opened as a URL.
Options: 
      -a                Opens with the specified application.
      -b                Opens with the specified application bundle identifier.
      -e                Opens with TextEdit.
      -t                Opens with default text editor.
      -f                Reads input from standard input and opens with TextEdit.
      -F  --fresh       Launches the app fresh, that is, without restoring windows. Saved persistent state is lost, excluding Untitled documents.
      -R, --reveal      Selects in the Finder instead of opening.
      -W, --wait-apps   Blocks until the used applications are closed (even if they were already running).
          --args        All remaining arguments are passed in argv to the application's main() function instead of opened.
      -n, --new         Open a new instance of the application even if one is already running.
      -j, --hide        Launches the app hidden.
      -g, --background  Does not bring the application to the foreground.
      -h, --header      Searches header file locations for headers matching the given filenames, and opens them.

**Comment by mandarl** [comment]
OS Version is El Capitan v10.11.5

**Comment by mandarl** [comment]
Adding --args seems to work. But if another chrome window is open then it just switches focus to that window without opening ex.html in an app window.

/usr/bin/open -a Google\ Chrome --args --disable-extension  -app=http://127.0.0.1:53482/ex.html

**Comment by mandarl** [comment]
Adding the -n option opens a new window if there is an existing window.

/usr/bin/open **-n** -a Google\ Chrome --args --disable-extension --new-window --app=http://127.0.0.1:53482/ex.html

**Comment by utamaro** [comment]
thanks for your information! :grinning: 

I'll fix the prog as your info.

**Comment by utamaro** [comment]
I believe I fixed the prog for OS X.

Try it if you don't mind.

**Comment by mandarl** [comment]
Still doesn't work. The command seems to be correct but there is an error in os.Stderr:

2016/10/05 19:41:55 /Users/mandarlimaye/golang/src/github.com/utamaro/neje-ui/backend/browser.go:83: executing /usr/bin/open -n -a Google\ Chrome --args --disable-extension  --new-window --app=http://127.0.0.1:58849/ex.html
**The file /Users/mandarlimaye/golang/src/github.com/utamaro/neje-ui/example/backend/Chrome does not exist.**

It seems to be trying to execute Chrome instead of Google\ Chrome. Let me check if I can find a workaround.

**Comment by mandarl** [comment]
Found the problem in browser.go(77):

**args := strings.Split(o, " ")**

This splits "Google\\ Chrome" into two arguments. It should be one.

**Comment by mandarl** [comment]
I have a hack pull request #9 to get this working for now. Will check if there is a more graceful way to do this.

**Comment by utamaro** [comment]
thanks!

**Comment by utamaro** [comment]
I'll try to change chome options from string to []string.

**Comment by utamaro** [comment]
changed :grinning:
